# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
#
# Configuration for benchmarks to be included in the Benchmark.AI report.
#
# If you would like to add a benchmark to the benchmark report, please follow the following convention, and check your
# configuration by generating a test report via the CLI.
#
# To generate a report, set the AWS environment variables described in report.py and run
#     'python report.py -f output'
# You can inspect output.xlsx and output.html to ensure they are as expected.
#
# The configuration format is as follows. All fields are optional unless specified as required.
#
#    - Metric Prefix: the metric prefix without trailing period  (required)
#      Metric Suffix: the metric suffix without leading period  (required)
#      DashboardUri: The URI for the dashboard (recommended, but not required).
#      Type: Training CV, Training NLP, Inference, or Model Import (required)
#      Framework: MXNet, Tensorflow, PyTorch, Caffe
#      Framework Desc: Gluon, Module, Symbol, Gluon Hybrid, Horovod, SageMaker
#      Model: the model architecture e.g. ResNet-50
#      Benchmark Desc: Benchmark description/hyperparameters/dataset
#      Instance Type: p3.18xlarge

#      ###  These keys for Inference tasks ###
#      Latency:
#      P50 Latency:
#      P90 Latency:
#
#      ###  These keys for Training CV tasks ###
#      Top 1 Val Acc:  the top-1 validation accuracy
#      Top 1 Train Acc: the top-1 training accuracy
#      Precision: the precision, e.g. FP16, FP32
#      Perplexity:
#
#      ###  These keys for Training NLP tasks ###
#      Precision: the precision, e.g. FP16, FP32
#      Perplexity:
#
#      ### Default values will be used for the keys. They do not need to be specified, but can be overridden if
#      ### necessary:
#      CPU Memory: cpu_memory_usage
#      GPU Memory Max: gpu_memory_usage_max
#      GPU Memory Mean: gpu_memory_usage_mean
#      Throughput: throughput
#      Time to Train: time_to_train
#      Uptime: uptime_in_seconds
#
benchmarks: 
# ------------------ Tensorflow MKL --------------------------------------------
  - Metric Prefix: mxnet.tensorflow_mkl_c5_resnet50_18xlg
    Metric Suffix: nightly.c5_18x
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=Training-Inference-TensorFlow-MKL"
    Type: Training CV
    Framework: Tensorflow
    Framework Desc: MKL
    Model: ResNet-50
    Benchmark Desc: Batch size 1
    Instance Type: c5.18xlarge
    Throughput: images/sec(training with batch size 1)

  - Metric Prefix: mxnet.tensorflow_mkl_c5_resnet50_18xlg
    Metric Suffix: nightly.c5_18x
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=Training-Inference-TensorFlow-MKL"
    Type: Training CV
    Framework: Tensorflow
    Framework Desc: MKL
    Model: ResNet-50
    Benchmark Desc: Batch size 32
    Instance Type: c5.18xlarge
    Throughput: images/sec(training with batch size 32)

# The Tensorflow MKL Inference benchmarks are not live.
# - Metric Prefix: mxnet.tensorflow_mkl_c5_resnet50_18xlg
#   Metric Suffix: nightly.c5_18x
#   DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=Training-Inference-TensorFlow-MKL"
#   Type: Inference
#   Framework: Tensorflow
#   Framework  Desc: MKL
#   Model: ResNet-50
#   Benchmark Desc: Batch size 1
#   Instance Type: c5.18xlarge
#   Throughput: images/sec(Inference with batch size 1)
#
# - Metric Prefix: mxnet.tensorflow_mkl_c5_resnet50_18xlg
#   Metric Suffix: nightly.c5_18x
#   DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=Training-Inference-TensorFlow-MKL"
#   Type: Inference
#   Framework: Tensorflow
#   Framework Desc: MKL
#   Model: ResNet-50
#   Benchmark Desc: Batch size 32
#   Instance Type: c5.18xlarge
#   Throughput: images/sec(Inference with batch size 32)

# ------------------ Tensorflow Horovod ----------------------------------------
  - Metric Prefix: mxnet.tensorflow_horovod_resnet50_p3_16xlg_batch_2048
    Metric Suffix: nightly.p3_16x
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=Training-TensorFlow-Horovod-Resnet50V1-Imagenet-GPU-8"
    Type: Training CV
    Framework: Tensorflow
    Framework Desc: Horovod
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Top 1 Val Acc: Top 1 accuracy
    Throughput: Images per sec
    Time to Train: Time-to-train (seconds)

# ------------------ DLAMI Training Benchmarks - MXNet -------------------------
  - Metric Prefix: mxnet.mxnet_p27_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_UL
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: MXNet
    Framework Desc: Gluon/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: speed(samples/sec)
    Benchmark Desc: p27-DLAMI-UL
    Precision: FP32

  - Metric Prefix: mxnet.mxnet_p27_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_AML
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: MXNet
    Framework Desc: Gluon/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: speed(samples/sec)
    Benchmark Desc: p27-DLAMI-AML
    Precision: FP32

  - Metric Prefix: mxnet.mxnet_p36_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_UL
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: MXNet
    Framework Desc: Gluon/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: speed(samples/sec)
    Benchmark Desc: p36-DLAMI-UL
    Precision: FP32

  - Metric Prefix: mxnet.mxnet_p36_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_AML
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: MXNet
    Framework Desc: Gluon/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: speed(samples/sec)
    Benchmark Desc: p36-DLAMI-AML
    Precision: FP32

# ------------------ DLAMI Training Benchmarks - Tensorflow --------------------
  - Metric Prefix: tensorflow.tensorflow_p27_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_UL
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: Tensorflow
    Framework Desc: MKL/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: Speed(Images/sec)
    Benchmark Desc: p27-DLAMI-UL
    Precision: FP32

  - Metric Prefix: tensorflow.tensorflow_p27_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_AML
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: Tensorflow
    Framework Desc: MKL/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: Speed(Images/sec)
    Benchmark Desc: p27-DLAMI-AML
    Precision: FP32

  - Metric Prefix: tensorflow.tensorflow_p36_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_UL
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: Tensorflow
    Framework Desc: MKL/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: Speed(Images/sec)
    Benchmark Desc: p36-DLAMI-UL
    Precision: FP32

  - Metric Prefix: tensorflow.tensorflow_p36_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_AML
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: Tensorflow
    Framework Desc: MKL/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: Speed(Images/sec)
    Benchmark Desc: p36-DLAMI-AML
    Precision: FP32

# ------------------ DLAMI Training Benchmarks - PyTorch -----------------------
  - Metric Prefix: pytorch.pytorch_p27_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_UL
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: PyTorch
    Framework Desc: MKL-DNN/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: speed(samples/sec)
    Benchmark Desc: p27-DLAMI-UL
    Precision: FP32

  - Metric Prefix: pytorch.pytorch_p27_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_AML
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: PyTorch
    Framework Desc: MKL-DNN/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: speed(samples/sec)
    Benchmark Desc: p27-DLAMI-AML
    Precision: FP32

  - Metric Prefix: pytorch.pytorch_p36_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_UL
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: PyTorch
    Framework Desc: MKL-DNN/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: speed(samples/sec)
    Benchmark Desc: p36-DLAMI-UL
    Precision: FP32

  - Metric Prefix: pytorch.pytorch_p36_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_AML
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: PyTorch
    Framework Desc: MKL-DNN/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: speed(samples/sec)
    Benchmark Desc: p36-DLAMI-AML
    Precision: FP32

# ------------------ DLAMI Training Benchmarks - Chainer -----------------------
  - Metric Prefix: chainer.chainer_p36_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_UL
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: Chainer
    Framework Desc: iDeep/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: speed(samples/sec)
    Benchmark Desc: p36-DLAMI-UL
    Precision: FP32

  - Metric Prefix: chainer.chainer_p36_resnet50_synthetic_fp32
    Metric Suffix: DLAMI_AML
    DashboardUri: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=DLAMI_Training_Performance"
    Type: Training CV
    Framework: Chainer
    Framework Desc: iDeep/Synthetic
    Model: ResNet-50
    Instance Type: p3.16xlarge
    Throughput: speed(samples/sec)
    Benchmark Desc: p36-DLAMI-AML
    Precision: FP32

# -----------------------------------------------------------------------------
